### ISSUE TITLE
Regular TextBox control influenced by Scintilla contro

### ISSUE THREAD

**Issue by ikorman** [desjarlais/Scintilla.NET#94] opened 2023-12-15 18:18 UTC
I have noticed that in some cases regular win forms TextBox control is influenced by Scintilla.Net control in way that caret on TextBox control is jumping back and forth just by moving the mouse over the text box control. This happens when on single forms TextBox, Scintilla and TabControl are placed.

**To Reproduce**
Create simple windows forms app, .Net 8, add text box control, scintilla control and tab control. Run it, type some text in textbox and observe caret behavior when mouse is moved over it. There are no events assigned, just simple placing controls on the forms and run it.

It noticed two workarounds so far that removes this behavior:
1. When in forms.designer.cs I comment out following line:  scintilla1.UseRightToLeftReadingLayout = false;
2. Or if I type something into scintilla control and press enter, the it stops. Adding text with the code, does not help -it has to by typed in

**Expected behavior**
There should not be any influence on regular textBox control in any way.

**Screenshots**
![2023-12-15 19_04_50-Form1](https://github.com/desjarlais/Scintilla.NET/assets/5569153/bd6cdfb7-2011-4754-98dc-408e37cf4184)

**Desktop (please complete the following information):**
 - Windows 11, .Net8, Visual Studio 17.8.3
 
Thx
Ivan

**Comment by desjarlais** [comment] 2023-12-23 05:08
This does repro, I'll look into it and see what I can find out.

**Comment by desjarlais** [comment] 2023-12-26 07:11
I think the problem is here https://github.com/desjarlais/Scintilla.NET/blob/4d44c4db34adedc58c62626450cc35ff4e94c52e/Shared/Scintilla.cs#L3316C22-L3316C22 in UseRightToLeftReadingLayout.  We are calling SCI_SETFOCUS, but I think we need to use SCI_GRABFOCUS instead so that the control can force focus and update.  With the control being so early in the form init, I don't think it is getting the focus and the update is waiting which is why manually clicking into the form works because the update could finish processing.

**Comment by ikorman** [comment] 2023-12-26 11:30
Great, what is next step? You will issue new package version?

Btw. I downloaded source code, added it as reference to my test app - everything compiles, but in VS designer toolbox there is no Scintilla control present, so can not be added to the form. I also tried source code test app, it works when compiled but in designer mode the Scintilla controls are not visible on the forms. Any idea what I'm doing wrong?

**Comment by desjarlais** [comment] 2023-12-26 15:37
Yes, next steps are to release a version with the changes so you can confirm the issue is fixed.  

As for the issue with the designer, I'm not sure what could be going on there.  After I release the fix, if you are still interested in getting that to work, send me the repro steps in a new issue and I'll take a look.

**Comment by desjarlais** [comment] 2023-12-28 15:06
This should be fixed in 5.3.3.12, let me know if you still see the issue.

**Comment by KarloX2** [comment] 2024-02-22 06:18
I'm currently using 5.3.2.9 (the latest stable available from NuGet at the time of writing) and I'm facing the same issue. I already have set `BiDirectionality = BiDirectionalDisplayType.Disabled` and still the cursor is jumping (in other edit controls!).

I found that by setting `CaretPeriod = 0` it is resolved, so that's my workaround for the time being.

**Comment by desjarlais** [comment] 2024-05-07 20:29
I still see this with textbox controls, need to give this another look

**Closed** 2024-05-09 14:31 UTC
Labels: bug
