### ISSUE TITLE
Lexer is obsolete 

### ISSUE THREAD

**Issue by Aghlara** [desjarlais/Scintilla.NET#106] opened 2024-02-09 23:36 UTC
**Context**
As `ScintillaNET` (https://github.com/jacobslusser/ScintillaNET) is archived and not supported anymore, I upgrade to `Scintilla.NET`. And `Lexer.Container` is not supported since `scintilla 5.0+` and with no default, lexer Null is accepted only.

With that, when I defined my own language, Styules and set Lexer.Null I do not get StyleNeeded notification anymore. 

** Project info:
 - TargetFramework: `.net8.0`
 - WinForms
 - OS: Windows

**Comment by desjarlais** [comment] 2024-02-11 05:44
We may have fixed this in Issue #92 , how are you reproducing this?  I've been able to get StyleNeeded by setting the LexerName to string.Empty, but I might be misunderstanding your scenario so a repro or sample would be helpful.

**Comment by Aghlara** [comment] 2024-02-11 06:07
Thanks, `string.Empty` did the job 
![image](https://github.com/desjarlais/Scintilla.NET/assets/5187409/1f78683c-275e-4005-a936-20c7a1a1e15c)

However, it should be set before setting `Styles`.

**Comment by desjarlais** [comment] 2024-02-12 05:00
Closing this out since it looks like it is fixed.

**Closed by desjarlais** 2024-02-12 05:00 UTC
Labels: bug
